### ISSUE TITLE
Cannot clone repo in Windows

### ISSUE THREAD

**Issue by kodaws** [andersy005/deep-learning-specialization-coursera#6]
Hi,
When cloning the repo, git fails with:
fatal: cannot create directory at '01-Neural-Networks-and-Deep-Learning/week4/Programming Assignments/Deep Neural Network Application: Image Classification': Invalid argument

There is a ':' in folder name, which is not permitted in Windows. Is it possible for you to modify the name?

**Comment by andersy005** [comment]
This is now fixed. It should work. I am closing this for now. Feel free to reopen it if the issue persists @kodaws.
